import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "../assets/sass/global.scss";

export const metadata: Metadata = {
  title: "François-Xavier Savary | Portfolio",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin', 'latin-ext'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal']
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={poppins.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
